.TH GMAILWATCHER "1" "OCT 2011" "gmailwatcher" "User Commands"

.SH NAME
gmailwatcher \- Desktop Gmail Notifier for Ubuntu

.SH SYNOPSIS
.B gmailwatcher
[\fIoptions\fR]

.SH DESCRIPTION

GmailWathcer is a desktop gmail notifier for the Ubuntu desktop. It support 
multiple gmail/gapps accounts and uses push notifications to instantly notify
about new mail. It was designed to work with the Unity desktop but can work in
Gnome Shell too without some missing features like launcher message count and 
messaging menu.
GmailWatcher uses IMAP to communicate with gmail servers. Please make sure you've
turned on IMAP and that 'GMAIL[ALL_MAIL]' folder is visible via imap.

.B gmailwatcher
was designed to be used with the
.B Gmail IMAP Protocol.
Please make sure IMAP is turned on in gmail and that ''[Gmail]/All_Mail' folder is
visible to IMAP clients.

.SH OPTIONS
.TP
\fB\-\-quite\-start
Does not show the starting notification.

.SH AUTHOR
.B gmailwatcher
is developed by Owais Lone <hello@owaislone.org>

